CREATE SEQUENCE APP_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TABLE PRODUCT 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(64 BYTE) NOT NULL
, CATEGORY VARCHAR2(64 BYTE) NOT NULL
, PRICE NUMBER NOT NULL
, CREATION_DATE DATE NOT NULL
, LAST_UPDATE_DATE DATE NOT NULL
, VERSION NUMBER DEFAULT 1 NOT NULL
);

INSERT INTO PRODUCT (ID, NAME, CATEGORY, PRICE, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (APP_SEQ.nextval, 'product6', 'books', 1500, SYSDATE, SYSDATE, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, PRICE, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (APP_SEQ.nextval, 'product7', 'toys', 500, SYSDATE, SYSDATE, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, PRICE, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (APP_SEQ.nextval, 'product8', 'accessories', 5000, SYSDATE, SYSDATE, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, PRICE, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (APP_SEQ.nextval, 'product9', 'toys', 700, SYSDATE, SYSDATE, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, PRICE, CREATION_DATE, LAST_UPDATE_DATE, VERSION) VALUES (APP_SEQ.nextval, 'product10', 'books', 2000, SYSDATE, SYSDATE, 1);